"use client";

import { MOCK_ORDERS, ORDERS_KEY, PRODUCTS, type DemoOrder, formatPrice } from "@/lib/demo-data";
import { BarChart3, CalendarDays, ChevronRight, CircleUserRound, Gem, LayoutDashboard, Package, Search, ShoppingBag, Sparkles, UsersRound, X } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";

const navigation = [
  ["Dashboard", LayoutDashboard], ["Zamówienia", ShoppingBag], ["Kalendarz", CalendarDays], ["Produkty", Gem], ["Klienci", UsersRound],
] as const;
const statusStyles: Record<string, string> = { "Nowe": "bg-violet-100 text-violet-900", "Opłacone": "bg-sky-100 text-sky-900", "W realizacji": "bg-amber-100 text-amber-900", "Wymaga kontaktu": "bg-rose-100 text-rose-900", "Gotowe do wysyłki": "bg-emerald-100 text-emerald-900", "Wysłane": "bg-stone-200 text-stone-800" };
const statusOptions = Object.keys(statusStyles);

export function AdminDemo() {
  const [tab, setTab] = useState("Dashboard");
  const [orders, setOrders] = useState<DemoOrder[]>(MOCK_ORDERS);
  const [selected, setSelected] = useState<DemoOrder | null>(null);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("Wszystkie");
  const dialogRef = useRef<HTMLDialogElement>(null);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      const local = JSON.parse(localStorage.getItem(ORDERS_KEY) ?? "[]") as DemoOrder[];
      setOrders([...local, ...MOCK_ORDERS.filter((mock) => !local.some((item) => item.id === mock.id))]);
    }, 0);
    return () => window.clearTimeout(timer);
  }, []);
  useEffect(() => { if (selected && !dialogRef.current?.open) dialogRef.current?.showModal(); }, [selected]);

  const filtered = useMemo(() => orders.filter((order) => (filter === "Wszystkie" || order.status === filter) && `${order.id} ${order.customer} ${order.product} ${order.stone}`.toLowerCase().includes(search.toLowerCase())), [orders, filter, search]);
  const updateStatus = (status: string) => {
    if (!selected) return;
    const updated = orders.map((order) => order.id === selected.id ? { ...order, status } : order);
    const nextSelected = { ...selected, status };
    setOrders(updated); setSelected(nextSelected);
    const localIds = (JSON.parse(localStorage.getItem(ORDERS_KEY) ?? "[]") as DemoOrder[]).map((order) => order.id);
    localStorage.setItem(ORDERS_KEY, JSON.stringify(updated.filter((order) => localIds.includes(order.id))));
  };

  return <div className="silk-page min-h-screen lg:grid lg:grid-cols-[16rem_1fr]">
    <aside className="bg-cocoa text-paper lg:sticky lg:top-0 lg:h-screen"><div className="flex min-h-16 items-center justify-between border-b border-paper/10 px-5 lg:min-h-20"><Link href="/" className="flex items-center gap-3"><span className="relative size-11 overflow-hidden rounded-full border border-paper/30 bg-paper"><Image src="/jewelry/splot-kamieni-logo.webp" alt="" fill className="object-cover" sizes="44px" /></span><span><strong className="font-editorial text-xl">Splot Kamieni</strong><small className="block text-[0.58rem] uppercase tracking-widest text-paper/45">Panel demo</small></span></Link></div><nav aria-label="Panel właścicielki" className="flex gap-1 overflow-x-auto p-3 lg:grid lg:p-4">{navigation.map(([label, Icon]) => <button key={label} type="button" onClick={() => setTab(label)} className={`flex min-h-11 shrink-0 items-center gap-3 rounded-2xl px-4 text-sm font-bold ${tab === label ? "bg-paper text-cocoa" : "text-paper/60 hover:bg-paper/10 hover:text-paper"}`}><Icon size={18} aria-hidden="true" />{label}</button>)}</nav><div className="mx-4 mt-auto hidden rounded-2xl bg-paper/10 p-4 lg:block"><p className="text-xs font-bold uppercase tracking-wider text-gold">Szybkie przejście</p><p className="mt-2 text-xs leading-5 text-paper/55">Pokaż klientce widok sklepu bez wylogowania.</p><Link href="/" className="mt-3 inline-flex min-h-11 items-center text-sm font-bold">Widok klienta <ChevronRight size={16} aria-hidden="true" /></Link></div></aside>

    <main id="main-content" className="min-w-0"><header className="flex min-h-20 items-center justify-between border-b border-line bg-paper px-5 sm:px-8"><div><p className="text-xs font-bold uppercase tracking-widest text-gold">Wersja demonstracyjna</p><h1 className="mt-1 font-sans text-xl font-extrabold">{tab}</h1></div><div className="flex items-center gap-3"><span className="hidden text-right text-xs sm:block"><strong className="block">Magdalena</strong><span className="text-cocoa/45">Właścicielka</span></span><CircleUserRound className="text-gold" size={34} aria-hidden="true" /></div></header><div className="p-5 sm:p-8">
      {tab === "Dashboard" && <Dashboard orders={orders} openOrder={setSelected} viewOrders={() => setTab("Zamówienia")} />}
      {tab === "Zamówienia" && <Orders orders={filtered} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} openOrder={setSelected} />}
      {tab === "Kalendarz" && <Calendar orders={orders} openOrder={setSelected} />}
      {tab === "Produkty" && <Products />}
      {tab === "Klienci" && <Customers orders={orders} />}
    </div></main>

    <dialog ref={dialogRef} onClose={() => setSelected(null)} className="m-auto max-h-[90vh] w-[min(44rem,calc(100%-2rem))] overflow-y-auto rounded-[2rem] border-0 bg-paper p-0 text-ink shadow-2xl backdrop:bg-cocoa/55">
      {selected && <div><div className="sticky top-0 z-10 flex items-start justify-between border-b bg-paper/95 p-6 backdrop-blur"><div><p className="eyebrow">Szczegóły zamówienia</p><h2 className="mt-1 text-3xl">{selected.id}</h2></div><button type="button" onClick={() => dialogRef.current?.close()} className="flex size-11 items-center justify-center rounded-full bg-ivory" aria-label="Zamknij szczegóły"><X aria-hidden="true" /></button></div><div className="grid gap-7 p-6 sm:grid-cols-[10rem_1fr]"><div className="relative aspect-square overflow-hidden rounded-2xl"><Image src={selected.image} alt={selected.product} fill className="object-cover" /></div><div><h3 className="text-3xl">{selected.product}</h3><p className="mt-2 text-sm text-cocoa/55">{selected.customer} · {selected.email}</p><label htmlFor="status" className="mt-5 block text-xs font-bold uppercase tracking-wider">Status zamówienia<select id="status" value={selected.status} onChange={(event) => updateStatus(event.target.value)} className="mt-2 min-h-12 w-full rounded-2xl border bg-ivory px-4 text-sm font-semibold normal-case tracking-normal">{statusOptions.map((status) => <option key={status}>{status}</option>)}</select></label></div></div><div className="grid gap-6 border-t p-6 sm:grid-cols-2"><Detail title="Personalizacja" rows={[["Kamień", selected.stone], ["Dodatki", selected.hardware], ["Rozmiar", selected.size], ["Zawieszka", selected.charm], ["Intencja", selected.customIntention || selected.intention], ["Dedykacja", selected.dedication || "Brak"], ["Opakowanie", selected.packaging]]} /><Detail title="Realizacja" rows={[["Termin", selected.dueDate], ["Dostawa", selected.delivery], ["Płatność", selected.payment], ["Wartość", formatPrice(selected.total)], ["Adres", selected.address], ["Telefon", selected.phone]]} /></div>{selected.note && <div className="mx-6 mb-6 rounded-2xl bg-blush p-4 text-sm"><strong>Notatka klientki:</strong> {selected.note}</div>}</div>}
    </dialog>
  </div>;
}

function Dashboard({ orders, openOrder, viewOrders }: { orders: DemoOrder[]; openOrder: (order: DemoOrder) => void; viewOrders: () => void }) {
  const stats = [["Nowe zamówienia", "12", ShoppingBag], ["W realizacji", "8", Sparkles], ["Do wysyłki", "4", Package], ["Przychód w lipcu", "6 420 zł", BarChart3]] as const;
  const bars = ["h-[42%]", "h-[66%]", "h-[38%]", "h-[78%]", "h-[55%]", "h-[91%]", "h-[70%]"];
  const stones = [["Kwarc różowy", "72%", "w-[72%]"], ["Ametyst", "58%", "w-[58%]"], ["Turmalin czarny", "43%", "w-[43%]"], ["Kamień księżycowy", "31%", "w-[31%]"]];
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Dzień dobry, Magdaleno</p><h2 className="mt-2 text-4xl">Co dziś dzieje się w pracowni?</h2></div><p className="text-sm text-cocoa/45">Poniedziałek, 20 lipca</p></div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value, Icon]) => <article key={label} className="soft-card p-5"><div className="flex items-start justify-between"><span className="flex size-10 items-center justify-center rounded-2xl bg-blush text-gold"><Icon size={18} aria-hidden="true" /></span><span className="text-xs text-green-800">+12%</span></div><p className="mt-7 text-3xl font-extrabold">{value}</p><p className="mt-1 text-xs text-cocoa/45">{label}</p></article>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_0.85fr]"><section className="soft-card p-6"><div className="flex justify-between"><div><p className="eyebrow">Ostatnie 7 dni</p><h3 className="mt-1 font-sans text-lg font-extrabold">Liczba zamówień</h3></div><strong>34</strong></div><div className="mt-8 flex h-48 items-end justify-between gap-3 border-b border-line px-2">{bars.map((height) => <div key={height} className="flex h-full flex-1 items-end"><div className={`w-full rounded-t-xl bg-gold/70 ${height}`} /></div>)}</div><div className="mt-3 flex justify-between text-[0.65rem] text-cocoa/40"><span>Pon</span><span>Wt</span><span>Śr</span><span>Czw</span><span>Pt</span><span>Sob</span><span>Nie</span></div></section><section className="soft-card p-6"><p className="eyebrow">Najpopularniejsze kamienie</p><h3 className="mt-1 font-sans text-lg font-extrabold">W tym miesiącu</h3><div className="mt-6 space-y-5">{stones.map(([name, value, width]) => <div key={name}><div className="mb-2 flex justify-between text-xs font-bold"><span>{name}</span><span>{value}</span></div><div className="h-2 rounded-full bg-sand"><div className={`h-2 rounded-full bg-gold ${width}`} /></div></div>)}</div></section></div><section className="mt-6 soft-card overflow-hidden"><div className="flex items-center justify-between p-6"><div><p className="eyebrow">Do zrobienia</p><h3 className="mt-1 font-sans text-lg font-extrabold">Najbliższe realizacje</h3></div><button type="button" onClick={viewOrders} className="min-h-11 text-sm font-bold text-gold">Zobacz wszystkie</button></div><OrderTable orders={orders.slice(0, 5)} openOrder={openOrder} /></section></div>;
}

function Orders({ orders, search, setSearch, filter, setFilter, openOrder }: { orders: DemoOrder[]; search: string; setSearch: (value: string) => void; filter: string; setFilter: (value: string) => void; openOrder: (order: DemoOrder) => void }) { return <div><div><p className="eyebrow">Obsługa zamówień</p><h2 className="mt-2 text-4xl">Wszystkie zamówienia</h2></div><div className="mt-7 flex flex-col gap-3 rounded-[2rem] border bg-paper p-4 sm:flex-row"><label className="relative flex-1" htmlFor="search-orders"><span className="sr-only">Szukaj zamówienia</span><Search className="absolute left-4 top-3.5 text-cocoa/35" size={17} aria-hidden="true" /><input id="search-orders" value={search} onChange={(event) => setSearch(event.target.value)} className="min-h-11 w-full rounded-full border bg-ivory pl-11 pr-4 text-sm" placeholder="Numer, klientka, produkt lub kamień" /></label><label htmlFor="status-filter"><span className="sr-only">Filtruj po statusie</span><select id="status-filter" value={filter} onChange={(event) => setFilter(event.target.value)} className="min-h-11 rounded-full border bg-ivory px-4 text-sm font-bold"><option>Wszystkie</option>{statusOptions.map((status) => <option key={status}>{status}</option>)}</select></label></div><div className="mt-5 soft-card overflow-hidden">{orders.length ? <OrderTable orders={orders} openOrder={openOrder} /> : <div className="p-12 text-center"><Search className="mx-auto text-gold" aria-hidden="true" /><h3 className="mt-4 text-3xl">Brak pasujących zamówień</h3><p className="mt-2 text-sm text-cocoa/50">Zmień filtr lub wpisaną frazę.</p></div>}</div></div>; }

function OrderTable({ orders, openOrder }: { orders: DemoOrder[]; openOrder: (order: DemoOrder) => void }) { return <div className="overflow-x-auto"><table className="w-full min-w-[52rem] text-left text-sm"><caption className="sr-only">Lista zamówień</caption><thead className="bg-ivory text-[0.65rem] uppercase tracking-wider text-cocoa/45"><tr><th scope="col" className="px-6 py-4">Numer</th><th scope="col" className="px-4 py-4">Klientka</th><th scope="col" className="px-4 py-4">Produkt</th><th scope="col" className="px-4 py-4">Wartość</th><th scope="col" className="px-4 py-4">Termin</th><th scope="col" className="px-4 py-4">Status</th><th scope="col" className="px-4 py-4"><span className="sr-only">Akcje</span></th></tr></thead><tbody>{orders.map((order) => <tr key={order.id} className="border-t border-line hover:bg-blush/40"><th scope="row" className="px-6 py-4 font-bold">{order.id}</th><td className="px-4 py-4">{order.customer}</td><td className="px-4 py-4 text-cocoa/60">{order.product}</td><td className="px-4 py-4 font-bold">{formatPrice(order.total)}</td><td className="px-4 py-4">{order.dueDate}</td><td className="px-4 py-4"><span className={`rounded-full px-3 py-1.5 text-[0.65rem] font-bold ${statusStyles[order.status] ?? "bg-stone-100"}`}>{order.status}</span></td><td className="px-4 py-4"><button type="button" onClick={() => openOrder(order)} className="flex size-11 items-center justify-center rounded-full hover:bg-sand" aria-label={`Otwórz zamówienie ${order.id}`}><ChevronRight size={17} aria-hidden="true" /></button></td></tr>)}</tbody></table></div>; }

function Calendar({ orders, openOrder }: { orders: DemoOrder[]; openOrder: (order: DemoOrder) => void }) { const days = Array.from({ length: 14 }, (_, index) => index + 20); return <div><p className="eyebrow">Lipiec 2026</p><h2 className="mt-2 text-4xl">Kalendarz realizacji</h2><p className="mt-3 text-sm text-cocoa/50">Kliknij wydarzenie, aby otworzyć zamówienie.</p><div className="mt-8 grid grid-cols-2 gap-px overflow-hidden rounded-[2rem] border bg-line sm:grid-cols-4 lg:grid-cols-7">{days.map((day, index) => { const order = orders[index % orders.length]; return <div key={day} className="min-h-40 bg-paper p-3"><p className="text-xs font-bold text-cocoa/45">{day} lip</p>{index % 3 !== 1 && <button type="button" onClick={() => openOrder(order)} className="mt-5 w-full rounded-2xl bg-blush p-3 text-left text-xs hover:-translate-y-0.5"><strong className="block">{order.id}</strong><span className="mt-1 block text-cocoa/55">{order.stone}</span><span className="mt-2 block text-[0.6rem] font-bold text-gold">{order.status}</span></button>}</div>; })}</div></div>; }
function Products() { return <div><p className="eyebrow">Katalog demo</p><h2 className="mt-2 text-4xl">Produkty</h2><div className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{PRODUCTS.map((product) => <article key={product.id} className="soft-card overflow-hidden"><div className="relative aspect-square"><Image src={product.image} alt={product.name} fill className="object-cover" /></div><div className="p-5"><span className="text-xs font-bold text-gold">{product.tag}</span><h3 className="mt-1 text-2xl">{product.name}</h3><div className="mt-4 flex justify-between text-sm"><span>Aktywny</span><strong>od {formatPrice(product.price)}</strong></div></div></article>)}</div></div>; }
function Customers({ orders }: { orders: DemoOrder[] }) { const unique = orders.filter((order, index) => orders.findIndex((item) => item.customer === order.customer) === index); return <div><p className="eyebrow">Relacje</p><h2 className="mt-2 text-4xl">Klientki</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{unique.slice(0, 9).map((order) => <article key={order.customer} className="soft-card flex items-center gap-4 p-5"><span className="flex size-12 shrink-0 items-center justify-center rounded-full bg-blush font-editorial text-xl text-gold">{order.customer.split(" ").map((part) => part[0]).join("")}</span><div><h3 className="font-sans text-sm font-extrabold">{order.customer}</h3><p className="mt-1 text-xs text-cocoa/45">{order.email}</p><p className="mt-2 text-xs font-bold text-gold">1 zamówienie · {formatPrice(order.total)}</p></div></article>)}</div></div>; }
function Detail({ title, rows }: { title: string; rows: string[][] }) { return <section><h3 className="font-sans text-sm font-extrabold">{title}</h3><dl className="mt-4 space-y-3 text-sm">{rows.map(([term, value]) => <div key={term}><dt className="text-xs text-cocoa/45">{term}</dt><dd className="mt-0.5 font-semibold">{value}</dd></div>)}</dl></section>; }
