import { DemoFooter, DemoHeader } from "@/components/demo-shell";
import { Check, CircleDot, Package, Truck } from "lucide-react";
import Link from "next/link";

const stages = ["Zamówienie złożone", "Płatność potwierdzona", "Przyjęte do realizacji", "Tworzenie biżuterii", "Gotowe do wysyłki", "Wysłane"];

export default async function TrackingPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  return <div><DemoHeader compact /><main id="main-content" className="shell min-h-[75vh] py-10 sm:py-16"><div className="grid gap-8 lg:grid-cols-[1fr_21rem]"><section><p className="eyebrow">Status zamówienia</p><h1 className="mt-2 text-5xl">Twój splot właśnie powstaje</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-cocoa/55">Każdy element jest dobierany i nawlekany ręcznie. Aktualny etap oznaczyliśmy poniżej.</p><ol className="mt-10 soft-card p-6 sm:p-9">{stages.map((stage, index) => { const done = index < 3; const active = index === 3; return <li key={stage} className="relative flex min-h-20 gap-5 last:min-h-0"><span className={`relative z-10 flex size-9 shrink-0 items-center justify-center rounded-full ${done ? "bg-sage text-paper" : active ? "bg-gold text-paper ring-4 ring-sand" : "border border-line bg-paper text-cocoa/30"}`}>{done ? <Check size={16} aria-hidden="true" /> : <CircleDot size={16} aria-hidden="true" />}</span>{index < stages.length - 1 && <span className={`absolute left-[1.1rem] top-9 h-[calc(100%-0.25rem)] w-px ${done ? "bg-sage" : "bg-line"}`} />}<div className="pt-1"><p className={`font-bold ${active ? "text-gold" : ""}`}>{stage}</p><p className="mt-1 text-xs text-cocoa/45">{active ? "Pracownia układa kompozycję i przygotowuje wykończenie." : done ? "Etap zakończony" : "Przed nami"}</p></div></li>; })}</ol></section><aside className="soft-card h-fit p-6 lg:sticky lg:top-24"><Package className="text-gold" aria-hidden="true" /><p className="eyebrow mt-6">Numer zamówienia</p><h2 className="mt-1 text-3xl">{id}</h2><dl className="mt-6 space-y-4 text-sm"><div><dt className="text-cocoa/45">Produkt</dt><dd className="font-bold">Bransoletka z intencją</dd></div><div><dt className="text-cocoa/45">Przewidywana wysyłka</dt><dd className="font-bold">28 lipca 2026</dd></div><div><dt className="text-cocoa/45">Dostawa</dt><dd className="font-bold">Paczkomat WAW01N</dd></div></dl><div className="mt-7 rounded-2xl bg-blush p-4 text-xs leading-5 text-cocoa/60"><Truck className="mb-2 text-gold" aria-hidden="true" /> Link do przewoźnika pojawi się po wysłaniu paczki.</div><Link href="/" className="button-secondary mt-6 w-full">Wróć do marki</Link></aside></div></main><DemoFooter /></div>;
}
